### ISSUE TITLE
气温和湿度 2019至今

### ISSUE THREAD

**Issue by yijunwang0805** [bsspirit/chinaWeather#1]
你好，

我想取气温和湿度做学术用途研究此次疫况。

我看到这份数据是2013年的，想问下你能更新这部分数据吗？

感谢。

Yijun

**Comment by bsspirit** [comment]
天气数据，我之前使用的YAHOO天气，https://developer.yahoo.com/weather/documentation.html
现在已经有很多开放的API了，你可以试试国内的天气API, https://www.jianshu.com/p/e3e04cf3fc0f

原来的获取方法：
http://blog.fens.me/r-app-china-weather/

**Comment by yijunwang0805** [comment]
谢谢！
